### ISSUE TITLE
Minor suggestions & bug report

### ISSUE THREAD

**Issue by benmarwick** [kmreese-io/Reese_and_Field_2021-AAP#1]
Hi Kelsey,

I'm a member of the AAP editorial board, and Sarah Herr asked me to review your code. I sent some comments to Sarah previously, and your updates look fantastic. You've done really great work making the readme so accessible and easy to follow! I'm sure it will be much appreciated by other archaeologists getting into this area. I've been working through your code and I have a few minor suggestions for improvement, and a bug report. 

## Minor suggestions

I'd suggest changing the title from "FOSS Protocol" to "FOSS UAV Protocol", because "FOSS Protocol" is very generic and gives almost no useful information to the reader about the specific domain of this project.

I recommend adding to the section "Updating" the software version numbers for the key pieces of software that are central to  the demo. Software changes over time, and their exact instructions may only work for a specific set of versions. If the reader can't make it work, but knows what versions the code worked with, they can take care to install those specific versions. Just typing the version numbers in the comments will be fine for this, like "For this demonstration we used R version 3.4.1, Python 3.7.0, etc.

In the section 'Installing Software and Defining an Area of Interest' I recommend adding a tiny bit of detail to say what each major dependency is for. For example, Docker is needed for OpenDroneMap. Then the user can get a clearer picture of how the pieces fit together and why they need to wait for all these things to install. If they have already previously installed something that will appear later in the instructions, they can make an informed decision at this point to skip it. 

In the section "Defining an Area of Interest", the instructions for creating a working directory are rather arbitrary and make many assumptions about user behaviour (e.g. that they have/use a Documents folder). Perhaps a more robust approach to tell the user to download the example files and set the working directory of their terminal to that location. Even more robust may be to give some the user some lines of bash to git clone the example-data from your GH repo, and then cd into that. You might mention that it's a 850 MB download, so the user can expect to wait a moment. If you use git clone, you don't need to assume anything about the user's computer and file system structure. 

We see './' many times in this section, which is an opaque way to reference a directory structure location and will be unclear to many users. Consider avoiding this using one of the approaches I mention above.

 base:: is not necessary in most places in the your code.

I recommend attaching an open source license (e.g. MIT) and a guide to contributors to your repository. This will help others to understand how they can use and reuse your materials here, and how to communicate with you if they have questions, requests, bug reports, etc. There are many good examples of these across GitHub, here's a repo with some that are suitable for your project that I've been working on recently: https://github.com/LiYingWang/kwl-burials 

 ## Bug report

I got an error in the section "Calculating Landcover Contexts" with this line

study.area.reprojected <- sp::spTransform(study.area,test@crs)

the error is 

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'CRSobj' in selecting a method for function 'spTransform': object 'test' not found

There is no code that creates an object called 'test'. Perhaps this was leftover from an earlier version? I don't know what to use instead of 'test' for this line.  

I could not proceed, but would be happy to keep testing if you can fix that line!

Here's my R session information:

```
sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] FedData_2.5.7 rgeos_0.5-5   raster_3.4-13 rgdal_1.5-23  sp_1.4-5     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        pillar_1.6.1      compiler_4.0.5    iterators_1.0.13 
 [5] tools_4.0.5       ncdf4_1.17        lubridate_1.7.10  lifecycle_1.0.0  
 [9] tibble_3.1.2      lattice_0.20-44   pkgconfig_2.0.3   rlang_0.4.11     
[13] foreach_1.5.1     DBI_1.1.1         dplyr_1.0.7       stringr_1.4.0    
[17] generics_0.1.0    vctrs_0.3.8       hms_1.1.0         grid_4.0.5       
[21] tidyselect_1.1.1  glue_1.4.2        data.table_1.14.0 R6_2.5.0         
[25] fansi_0.5.0       purrr_0.3.4       readr_2.0.0       tzdb_0.1.2       
[29] magrittr_2.0.1    codetools_0.2-18  ellipsis_0.3.2    assertthat_0.2.1 
[33] utf8_1.2.1        stringi_1.7.3     crayon_1.4.1 
```

**Comment by kmreese-io** [comment]
Hi Ben,

Thank you so much for looking through this code a couple times. I really appreciate your feedback and am happy to have made the instructions for the protocol much more user friendly through your suggestions.

I changed the title of the protocol both in the instructions and the code.
I added the package versions for everything in the introduction blurb.
I added a note that Docker and Docker Machine are required for OpenDroneMap.
I fixed the bug that used the “test” object to look up the projection. I was making sure I correctly called the projection system and forgot to switch out the object when putting it into its final version.
I have also added/appended a couple lines of code to create a file structure within which everything is run on the end user’s computer, and then use 'git clone’ to automatically download everything into that file structure. My goal is to create something that can be used by just running lines of code from start to finish without the need for the end user to change anything (I could see someone who does not really know how to code replacing the shapefiles and images within the file structure this code creates and being able to run everything without ever needing to know how to use R or command line tools more generally). I think if someone knows the ins-and-outs of all the tools being used here (such as yourself), then the exact step and file pathways can be changed to suit those specific needs because that person would not be afraid to get into the code and move things around. The protocol is meant to provide a standardized structure to collect and process UAV imagery, but I think can be expanded upon based on the individual’s needs and coding capabilities. That is all to say - I did not change the ‘./‘ portions of the code because if everything is run from start-to-finish, the correct structure is there and does not need to assume what everyone’s file structure looks like beyond the project folder.
I added a note in both the introduction and by the code chunk that the repository is a large download and therefore might take a little while.
I know ‘base::’ is not necessary, but prefer the consistency. It also seamlessly shares with the end user where all of the functions are coming from without needing to look anything up.

Thank you, again, for looking through all of this. My changes are up and published on Github and I am excited to see this all come to fruition!

All the best,
Kelsey

Kelsey M. Reese
Postdoctoral Teaching Scholar
Department of Anthropology
***@***.***

**Comment by benmarwick** [comment]
Hi Kelsey,

Thanks for your response and updates, that is all great to see, and makes your already excellent repository a really great example for others. 

Perhaps you missed my earlier suggestion to add an open source license (e.g. MIT) and a guide to contributors to your repository? These are considered standard components of a software project by many developers, and they are important for guiding people, especially novices, in how to interact with you about your project. 

I highly recommend you add them to your project here. There are many good templates and examples on GitHub, [here's a licence](https://github.com/LiYingWang/kwl-burials/blob/master/LICENSE.md) and here's a [guide to contributors ](https://github.com/LiYingWang/kwl-burials/blob/master/CONTRIBUTING.md) that you could use. Many developers also like to have a code of conduct document on their repository to be upfront about their expectations about behaviours when communicating about the project. Here's a typical [code of conduct](https://github.com/LiYingWang/kwl-burials/blob/master/CONDUCT.md) you could use. Although your code will still work without these documents in your repo, I believe they are important for contributing to a welcoming, accessible, inclusive and diverse community of computational archaeologists. I hope you will consider to add them.

warmly,

Ben

**Comment by kmreese-io** [comment]
Hi Ben,

I did miss those earlier suggestions - please forgive my oversight and thank you for sending a follow-up. I will look into each of these things and add them to the repository!

All the best,
Kelsey

Kelsey M. Reese
Postdoctoral Teaching Scholar
Department of Anthropology
***@***.***
